version: '3.8'
services:
    node_server:
        build: .
        container_name: node_server
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
            DB_HOST: userprojects-pg
            DB_PORT: 5432
            DB_USER: admin
            DB_PASSWORD: secret
            DB_NAME: userprojects
            JWT_SECRET: a09as,9masd@a
            PORT: 3000
        restart: unless-stopped
        profiles:
            - server
            - full

    userprojects-pg:
        container_name: userprojects-pg
        image: postgres:13.5-alpine
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_DB: userprojects
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data
            PGPORT: 5432
        ports:
            - '5432:5432'
        volumes:
            - userprojects-db-data:/var/lib/postgresql/data
        profiles:
            - full
            - db

    userprojects-pgadmin:
        container_name: userprojects-pgadmin
        image: dpage/pgadmin4:5.5
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        ports:
            - '8080:80'
        volumes:
            - userprojects-pgadmin-data:/var/lib/pgadmin
        profiles:
            - full
            - db

volumes:
    userprojects-db-data:
    userprojects-pgadmin-data:
